language: node_js
node_js:
  - "14.15.0"
before_install:
  - openssl aes-256-cbc -K $encrypted_e28d423744bc_key -iv $encrypted_e28d423744bc_iv -in env.json.enc -out env.json -d
install:
  - travis_retry yarn install --network-concurrency 1 --child-concurrency 1 --ignore-optional
script:
  - yarn lint
  - yarn flow
  - npm run test -- --runInBand --detectOpenHandles --coverage
